[toolchain]
channel = "1.95.0"
components = [
    "clippy",
    "llvm-tools",
    "rust-analyzer",
    "rust-src",
    "rustfmt",
]
targets = [
    "aarch64-unknown-none",
    "aarch64-unknown-none-softfloat",
    "armv7a-none-eabi",
    "armv7a-none-eabihf",
    "armv7r-none-eabi",
    "armv7r-none-eabihf",
    "armv8r-none-eabihf",
    # "loongarch64-unknown-none",
    # "loongarch64-unknown-none-softfloat",
    # "riscv32i-unknown-none-elf",
    # "riscv32im-unknown-none-elf",
    # "riscv32imac-unknown-none-elf",
    # "riscv32imafc-unknown-none-elf",
    # "riscv32imc-unknown-none-elf",
    # "riscv64gc-unknown-none-elf",
    # "riscv64imac-unknown-none-elf",
    "thumbv6m-none-eabi",
    "thumbv7em-none-eabi",
    "thumbv7em-none-eabihf",
    "thumbv7m-none-eabi",
    "thumbv8m.base-none-eabi",
    "thumbv8m.main-none-eabi",
    "thumbv8m.main-none-eabihf",
    # "wasm32v1-none",
    # "x86_64-unknown-none",
]
profile = "minimal"
